### ISSUE TITLE
Crash with Kinetic

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [ethz-asl/rqt_multiplot_plugin#2]
Hi,

I've followed the instruction to build from source to try to use multiplot on Ubuntu 16.04 with Ros kinetic.
The cakin_make process was successful but unfortunately the plugin encounter a issue at launch.

If launch through rqt, rqt crash without warning.
If launch with rosrun rqt_multiplot rqt_multiplot, the following error is observed: Segmentation fault (core dumped)

Is their specific step/workaround to use this tool with Kinetic?

Thanks

**Comment by samuelba** [comment]
There is a kinetic-devel branch, that should work with ROS Kinetic, please build this branch until the branch is merged into master.

**Comment by AlexandreBorowczyk** [comment]
Hi, thx for the tip.
I've build from the kinetic-devel, I'm now able to launch rqt_multiplot and view plot from rosbag when using the import from bag file feature. However when trying to plot from topics it doesn't work.

**Comment by samuelba** [comment]
Thanks for reporting, that's a bug. In QT5 they changed the function declaration of `connectNotify` from the `QObject` class. I'll fix that.

**Comment by samuelba** [comment]
fixed with the latest commit on kinetic-devel.

**Comment by AlexandreBorowczyk** [comment]
Hi,
Pulled un latest kinetic-devel, everything works great! 
Thanks

**Comment by vinbo** [comment]
not work on me, not know why...

**Comment by vinbo** [comment]
not work on me, not knowing why...
what's different is my rqt is working, but not rqt_multiplot

**Comment by vinbo** [comment]
> fixed with the latest commit on kinetic-devel.

still not work, with the kinetic-devel, any idea? thanks
