### ISSUE TITLE
found no plugin matching "MultiplotPlugin"

### ISSUE THREAD

**Issue by imrasp** [ethz-asl/rqt_multiplot_plugin#23]
I have successfully installed rat_multiplot via `sudo apt-get install ros-kinetic-rqt-multiplot` and got the error below while running via `rqt_multiplot` or `rosrun rqt_multiplot rqt_multiplot`
```
qt_gui_main() found no plugin matching "MultiplotPlugin"
```

Anyone know how to fix this kind of issue please help me out.

this is a part result from `ls /opt/ros/kinetic/lib` 
```
...
rqt_bag
rqt_console
rqt_dep
rqt_graph
rqt_gui
rqt_image_view
rqt_launch
rqt_logger_level
rqt_moveit
rqt_msg
rqt_multiplot
rqt_nav_view
rqt_plot
rqt_pose_view
rqt_publisher
rqt_py_console
rqt_reconfigure
rqt_robot_monitor
rqt_robot_steering
rqt_runtime_monitor
rqt_rviz
rqt_service_caller
rqt_shell
rqt_srv
rqt_tf_tree
rqt_top
rqt_topic
rqt_web
...
```

**Comment by emaggard** [comment]
I had the same problem.  Run the following:

rqt --force-discover

then restart the rqt_multiplot plugin:

rosrun rqt_multiplot rqt_multiplot

**Comment by imrasp** [comment]
Thank you so much :) 
Finally, it work!
