### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [ethz-asl/rqt_multiplot_plugin#4]
Hi,

I've been having this issue when trying plot multiple rows (more then 2 rows on 1920X1080) when the plot window resize and the lower plots are out of bound. Up to now I've always cycled the "toggle floating" feature to fix it but it's only momentary. Do you know any method to fix it?

Thanks

Alexandre

**Comment by samuelba** [comment]
Thanks for reporting. Until the change makes it into the master branch you can checkout the fix/plot-resizing branch with the fix.

**Comment by AlexandreBorowczyk** [comment]
Tested the fix, works great! Thanks again!
