### ISSUE TITLE
Issues with custom topic message

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [ethz-asl/rqt_multiplot_plugin#6]
Hi,

I've run-in a other problem. When I'm trying to plot a custom message, it seems that it not plotting the right component.

For a exemple if my message had X, Y, Z component and I tried to plot all of then, it would plot Y, X, X or something like that.

Thanks

**Comment by samuelba** [comment]
Sorry, but I cannot reproduce that with our custom messages. Can you maybe provide me with a bag file and your plot configuration file?

**Comment by AlexandreBorowczyk** [comment]
Sorry, I've lost the data and it's seems I cannot reproduce it either.
